-- =====================================================================
-- live_schema_check.sql - does the live database match the migrations?
--
-- GENERATED by scripts/build-live-check.js from supabase/migrations
-- (0001_initial_schema.sql .. 0030_drop_leftover_function_versions.sql). Do not edit by hand.
--
-- Paste the whole file into the Supabase SQL Editor and Run. It changes
-- nothing: it reads the catalog, and the policy comparison creates copies
-- of the expected rules inside a block that is always rolled back.
--
-- The result lists ONLY differences, after one summary row:
--   function  differs     live body/settings are not the repo's latest
--   function  left over   an old version the migrations meant to drop
--   policy    differs / missing / left over
--   trigger   missing / left over / calls a different function
--   table     row security OFF
-- Expected: the summary row says 0 problems.
-- =====================================================================

DROP TABLE IF EXISTS pg_temp.absl_expected_function;
CREATE TEMP TABLE absl_expected_function (signature text, body_md5 text, secdef boolean, volatility "char", config text, source text);
INSERT INTO absl_expected_function VALUES
    ('"public"."set_updated_at"()', 'd258fba5feeb9ce8126471bef81c3228', false, 'v', '', '0001_initial_schema.sql'),
    ('"public"."assign_ticket_number"()', 'b860fd149f595312c0de4aeb38cc74be', false, 'v', '', '0001_initial_schema.sql'),
    ('"public"."current_role"()', 'f7756bf25d6e1008fc808584d1d9a448', true, 's', 'search_path=public', '0003_security_hardening.sql'),
    ('"public"."can_view_ticket"(public.tickets)', '537de61dfdc91031ac8416f12149609f', true, 's', 'search_path=public', '0029_null_safe_role_checks.sql'),
    ('"public"."log_ticket_status_change"()', '8454064771b04280e742edd39efec41e', true, 'v', 'search_path=public', '0001_initial_schema.sql'),
    ('"public"."consume_inventory"(uuid, uuid, integer)', '6187b133a0a14bf86e179f2a134bed70', true, 'v', 'search_path=public', '0029_null_safe_role_checks.sql'),
    ('"public"."queue_ticket_notification"()', '2b20de18430324ecfeceed51a1583601', true, 'v', 'search_path=public', '0027_no_self_emails_for_staff_jobs.sql'),
    ('"public"."can_view_ticket"(uuid)', '8ffda86da1d2f3d074de8649b72296d5', true, 's', 'search_path=public', '0002_production_ready.sql'),
    ('"public"."handle_new_user"()', 'c81e06f5fc9a9f21dfa3a64a1dd0e971', true, 'v', 'search_path=public,auth', '0021_department_phone_location.sql'),
    ('"public"."queue_dead_letter_alert"()', 'b184c6bdc38d114804cdfdf719e1d3ea', true, 'v', 'search_path=public', '0002_production_ready.sql'),
    ('"public"."is_admin"()', 'b640449e36d713372e5f08b3610de605', true, 's', 'search_path=public', '0003_security_hardening.sql'),
    ('"public"."is_staff"()', '100f39788d5d33033b01cd55a646a64e', true, 's', 'search_path=public', '0029_null_safe_role_checks.sql'),
    ('"public"."guard_profile_privileges"()', '0f29f09cfc0c2ac3b822459a565b5448', true, 'v', 'search_path=public', '0003_security_hardening.sql'),
    ('"public"."admin_review_registration"(uuid, boolean, public.user_role, text)', 'd9bd55bdb649890f4c72bdae80822696', true, 'v', 'search_path=public', '0015_registration_decision_email.sql'),
    ('"public"."guard_ticket_fields"()', '06be593b8577715b479ea2c611341123', true, 'v', 'search_path=public', '0003_security_hardening.sql'),
    ('"public"."claim_notifications"(integer)', 'd3c6fec182fb51dc9fc9181bf03202a8', true, 'v', 'search_path=public', '0003_security_hardening.sql'),
    ('"public"."can_access_ticket_file"(text)', '9538b047e15e91504cdecc03f29f68b4', true, 's', 'search_path=public', '0003_security_hardening.sql'),
    ('"public"."request_callback"(uuid, text)', '037cbdbcd2e502f7f40946d9ddd73e36', true, 'v', 'search_path=public', '0004_feature_completion.sql'),
    ('"public"."complete_callback"(uuid, text)', 'a20271bbc3af5bbce3e2d2037ece0e36', true, 'v', 'search_path=public', '0029_null_safe_role_checks.sql'),
    ('"public"."reassign_ticket"(uuid, uuid, text)', 'e0ed7a60cbcbeae2c794c5ada7e5b412', true, 'v', 'search_path=public', '0022_open_job_pool.sql'),
    ('"public"."queue_comment_notification"()', '90d35514d67a140d7fef91b25b109819', true, 'v', 'search_path=public', '0024_operator_role_permissions.sql'),
    ('"public"."audit_ticket_change"()', '0480af97cc3841930dfe480c95745f29', true, 'v', 'search_path=public', '0004_feature_completion.sql'),
    ('"public"."ticket_detail"(uuid)', 'b00dade95b87c5b323adef7d4fa132f9', true, 's', 'search_path=public', '0004_feature_completion.sql'),
    ('"public"."generate_ticket_receipt"()', 'c01121c48e80eac10cdf2e7fd2c92a3c', true, 'v', 'search_path=public', '0010_receipt_enrichment.sql'),
    ('"public"."change_ticket_status"(uuid, public.ticket_status, integer, text, text)', '42c96a9770ca3e4b98f65d9c0457ac62', true, 'v', 'search_path=public', '0011_resolution_evidence_all_staff.sql'),
    ('"public"."add_progress_photo"(uuid, text, text, bigint, text, text, text)', '28e54534fa708b3d906d7e6b05388f08', true, 'v', 'search_path=public', '0012_audit_fixes_round2.sql'),
    ('"public"."report_search"(text, text, date, date, text, text, uuid, text)', '66c8169175546ffff28bbc962f3ee45c', true, 's', 'search_path=public', '0018_ticket_job_type.sql'),
    ('"public"."discard_orphaned_receipt_attachment"(uuid)', 'a19e994a98fa20903b300d783c5feec7', true, 'v', 'search_path=public', '0019_audit_fixes_round3.sql'),
    ('"public"."trigger_send_notifications"()', '6a02e58e349b2b044be2a49cd9f401ad', true, 'v', 'search_path=public,extensions', '0020_auto_send_notifications_webhook.sql'),
    ('"public"."release_ticket_to_pool"(uuid)', 'ff0ae8a1807a1724583003f374798e8e', true, 'v', 'search_path=public', '0029_null_safe_role_checks.sql'),
    ('"public"."staff_log_ticket"(text, text, text, text, text, text, text, text, text, boolean, boolean)', 'a026d5990dc68da5fc6af9cc00afb137', true, 'v', 'search_path=public', '0029_null_safe_role_checks.sql'),
    ('"public"."report_jobs"(date, date)', 'e2bcc67d1674d716c2f788cb54fe8fca', true, 's', 'search_path=public', '0029_null_safe_role_checks.sql');

DROP TABLE IF EXISTS pg_temp.absl_expected_trigger;
CREATE TEMP TABLE absl_expected_trigger (schema_name text, table_name text, trigger_name text, function_name text, source text, optional boolean);
INSERT INTO absl_expected_trigger VALUES
    ('public', 'companies', 'set_companies_updated_at', 'set_updated_at', '0001_initial_schema.sql', false),
    ('public', 'profiles', 'set_profiles_updated_at', 'set_updated_at', '0001_initial_schema.sql', false),
    ('public', 'tickets', 'set_tickets_updated_at', 'set_updated_at', '0001_initial_schema.sql', false),
    ('public', 'inventory_items', 'set_inventory_items_updated_at', 'set_updated_at', '0001_initial_schema.sql', false),
    ('public', 'tickets', 'assign_ticket_number', 'assign_ticket_number', '0001_initial_schema.sql', false),
    ('public', 'tickets', 'log_ticket_status_insert', 'log_ticket_status_change', '0001_initial_schema.sql', false),
    ('public', 'tickets', 'log_ticket_status_update', 'log_ticket_status_change', '0001_initial_schema.sql', false),
    ('public', 'tickets', 'queue_ticket_notification_insert', 'queue_ticket_notification', '0001_initial_schema.sql', false),
    ('public', 'tickets', 'queue_ticket_notification_update', 'queue_ticket_notification', '0001_initial_schema.sql', false),
    ('public', 'notifications', 'on_notification_dead_letter', 'queue_dead_letter_alert', '0002_production_ready.sql', false),
    ('auth', 'users', 'on_auth_user_created', 'handle_new_user', '0003_security_hardening.sql', false),
    ('public', 'profiles', 'guard_profile_privileges', 'guard_profile_privileges', '0003_security_hardening.sql', false),
    ('public', 'tickets', 'guard_ticket_fields', 'guard_ticket_fields', '0003_security_hardening.sql', false),
    ('public', 'ticket_comments', 'queue_comment_notification', 'queue_comment_notification', '0004_feature_completion.sql', false),
    ('public', 'tickets', 'audit_ticket_insert', 'audit_ticket_change', '0004_feature_completion.sql', false),
    ('public', 'tickets', 'audit_ticket_status', 'audit_ticket_change', '0004_feature_completion.sql', false),
    ('public', 'tickets', 'on_ticket_resolved', 'generate_ticket_receipt', '0005_video_receipts_site_contact.sql', false),
    ('public', 'notifications', 'trg_send_notifications', 'trigger_send_notifications', '0020_auto_send_notifications_webhook.sql', true);

DROP TABLE IF EXISTS pg_temp.absl_expected_policy;
CREATE TEMP TABLE absl_expected_policy (n integer, schema_name text, table_name text, policy_name text, source text, check_sql text);
INSERT INTO absl_expected_policy VALUES
    (1, 'public', 'companies', 'Admins manage companies', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_1"
on public.companies for all
to authenticated
using (public.current_role() = 'admin')
with check (public.current_role() = 'admin')$absl_q$),
    (2, 'public', 'profiles', 'Users update own basic profile', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_2"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid())$absl_q$),
    (3, 'public', 'profiles', 'Admins manage profiles', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_3"
on public.profiles for all
to authenticated
using (public.current_role() = 'admin')
with check (public.current_role() = 'admin')$absl_q$),
    (4, 'public', 'tickets', 'Tickets visible by role', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_4"
on public.tickets for select
to authenticated
using (public.can_view_ticket(tickets))$absl_q$),
    (5, 'public', 'tickets', 'Approved customers create tickets', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_5"
on public.tickets for insert
to authenticated
with check (
  created_by = auth.uid()
  and exists (
    select 1 from public.profiles
    where id = auth.uid()
      and approval_status = 'approved'
  )
)$absl_q$),
    (6, 'public', 'ticket_comments', 'Ticket comments visible with ticket', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_6"
on public.ticket_comments for select
to authenticated
using (
  exists (
    select 1 from public.tickets
    where tickets.id = ticket_comments.ticket_id
      and public.can_view_ticket(tickets)
  )
)$absl_q$),
    (7, 'public', 'ticket_comments', 'Ticket comments insert with ticket', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_7"
on public.ticket_comments for insert
to authenticated
with check (
  author_id = auth.uid()
  and exists (
    select 1 from public.tickets
    where tickets.id = ticket_comments.ticket_id
      and public.can_view_ticket(tickets)
  )
)$absl_q$),
    (8, 'public', 'ticket_attachments', 'Ticket attachments visible with ticket', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_8"
on public.ticket_attachments for select
to authenticated
using (
  exists (
    select 1 from public.tickets
    where tickets.id = ticket_attachments.ticket_id
      and public.can_view_ticket(tickets)
  )
)$absl_q$),
    (9, 'public', 'ticket_attachments', 'Ticket attachments insert with ticket', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_9"
on public.ticket_attachments for insert
to authenticated
with check (
  uploaded_by = auth.uid()
  and exists (
    select 1 from public.tickets
    where tickets.id = ticket_attachments.ticket_id
      and public.can_view_ticket(tickets)
  )
)$absl_q$),
    (10, 'public', 'inventory_items', 'Inventory visible to staff', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_10"
on public.inventory_items for select
to authenticated
using (public.current_role() in ('agent', 'technician', 'admin'))$absl_q$),
    (11, 'public', 'inventory_items', 'Admins manage inventory', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_11"
on public.inventory_items for all
to authenticated
using (public.current_role() = 'admin')
with check (public.current_role() = 'admin')$absl_q$),
    (12, 'public', 'notifications', 'Notifications visible to recipient and admin', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_12"
on public.notifications for select
to authenticated
using (
  recipient_profile_id = auth.uid()
  or public.current_role() = 'admin'
)$absl_q$),
    (13, 'public', 'notification_attempts', 'Admins read notification attempts', '0001_initial_schema.sql', $absl_q$CREATE POLICY "__absl_check_13"
on public.notification_attempts for select
to authenticated
using (public.current_role() = 'admin')$absl_q$),
    (14, 'public', 'callback_requests', 'Customers can view their own callback requests', '0002_production_ready.sql', $absl_q$CREATE POLICY "__absl_check_14"
  ON public.callback_requests
  FOR SELECT
  TO authenticated
  USING (requested_by = auth.uid())$absl_q$),
    (15, 'public', 'callback_requests', 'Customers can insert their own callback requests', '0002_production_ready.sql', $absl_q$CREATE POLICY "__absl_check_15"
  ON public.callback_requests
  FOR INSERT
  TO authenticated
  WITH CHECK (
    requested_by = auth.uid()
    AND public.can_view_ticket(ticket_id)
  )$absl_q$),
    (16, 'public', 'ticket_status_history', 'Visible to anyone who can view the related ticket', '0002_production_ready.sql', $absl_q$CREATE POLICY "__absl_check_16"
  ON public.ticket_status_history
  FOR SELECT
  TO authenticated
  USING (public.can_view_ticket(ticket_id))$absl_q$),
    (17, 'public', 'inventory_movements', 'Visible to staff', '0002_production_ready.sql', $absl_q$CREATE POLICY "__absl_check_17"
  ON public.inventory_movements
  FOR SELECT
  TO authenticated
  USING (public.current_role() IN ('agent', 'technician', 'admin'))$absl_q$),
    (18, 'public', 'inventory_movements', 'Insert by technician and admin only', '0002_production_ready.sql', $absl_q$CREATE POLICY "__absl_check_18"
  ON public.inventory_movements
  FOR INSERT
  TO authenticated
  WITH CHECK (
    public.current_role() IN ('technician', 'admin')
    AND technician_id = auth.uid()
  )$absl_q$),
    (19, 'public', 'audit_logs', 'Visible to admin only', '0002_production_ready.sql', $absl_q$CREATE POLICY "__absl_check_19"
  ON public.audit_logs
  FOR SELECT
  TO authenticated
  USING (public.current_role() = 'admin')$absl_q$),
    (20, 'public', 'audit_logs', 'Insert by authenticated users', '0002_production_ready.sql', $absl_q$CREATE POLICY "__absl_check_20"
  ON public.audit_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (actor_id = auth.uid())$absl_q$),
    (21, 'public', 'tickets', 'Creator updates own new ticket', '0003_security_hardening.sql', $absl_q$CREATE POLICY "__absl_check_21"
  ON public.tickets
  FOR UPDATE
  TO authenticated
  USING (created_by = auth.uid() AND status = 'new')
  WITH CHECK (created_by = auth.uid())$absl_q$),
    (22, 'public', 'tickets', 'Admins delete tickets', '0003_security_hardening.sql', $absl_q$CREATE POLICY "__absl_check_22"
  ON public.tickets
  FOR DELETE
  TO authenticated
  USING (public.is_admin())$absl_q$),
    (23, 'public', 'ticket_comments', 'Author or admin deletes comment', '0003_security_hardening.sql', $absl_q$CREATE POLICY "__absl_check_23"
  ON public.ticket_comments
  FOR DELETE
  TO authenticated
  USING (author_id = auth.uid() OR public.is_admin())$absl_q$),
    (24, 'public', 'notifications', 'Admins update notifications', '0003_security_hardening.sql', $absl_q$CREATE POLICY "__absl_check_24"
  ON public.notifications
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin())$absl_q$),
    (25, 'public', 'approval_requests', 'Own approval request visible', '0003_security_hardening.sql', $absl_q$CREATE POLICY "__absl_check_25"
  ON public.approval_requests
  FOR SELECT
  TO authenticated
  USING (profile_id = auth.uid() OR public.current_role() IN ('agent', 'admin'))$absl_q$),
    (26, 'public', 'approval_requests', 'Admins update approval requests', '0003_security_hardening.sql', $absl_q$CREATE POLICY "__absl_check_26"
  ON public.approval_requests
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin())$absl_q$),
    (27, 'public', 'inventory_items', 'Staff read inventory', '0003_security_hardening.sql', $absl_q$CREATE POLICY "__absl_check_27"
  ON public.inventory_items
  FOR SELECT
  TO authenticated
  USING (public.current_role() IN ('agent', 'technician', 'admin'))$absl_q$),
    (28, 'storage', 'objects', 'Inventory imports are admin only', '0003_security_hardening.sql', $absl_q$CREATE POLICY "__absl_check_28"
  ON storage.objects
  FOR ALL
  TO authenticated
  USING (bucket_id = 'inventory-csv-imports' AND public.is_admin())
  WITH CHECK (bucket_id = 'inventory-csv-imports' AND public.is_admin())$absl_q$),
    (29, 'public', 'ticket_receipts', 'Admins view receipts', '0005_video_receipts_site_contact.sql', $absl_q$CREATE POLICY "__absl_check_29"
  ON public.ticket_receipts
  FOR SELECT
  TO authenticated
  USING (public.is_admin())$absl_q$),
    (30, 'storage', 'objects', 'Ticket files readable by ticket viewers', '0007_service_call_receipt.sql', $absl_q$CREATE POLICY "__absl_check_30"
  ON storage.objects
  FOR SELECT
  TO authenticated
  USING (
    bucket_id IN ('ticket-photos', 'ticket-voice-notes', 'ticket-videos', 'ticket-service-receipts')
    AND public.can_access_ticket_file(name)
  )$absl_q$),
    (31, 'storage', 'objects', 'Ticket files uploadable by ticket viewers', '0007_service_call_receipt.sql', $absl_q$CREATE POLICY "__absl_check_31"
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id IN ('ticket-photos', 'ticket-voice-notes', 'ticket-videos', 'ticket-service-receipts')
    AND owner = auth.uid()
    AND public.can_access_ticket_file(name)
  )$absl_q$),
    (32, 'public', 'client_error_logs', 'Users report their own client errors', '0008_client_error_log.sql', $absl_q$CREATE POLICY "__absl_check_32"
  ON public.client_error_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (profile_id = auth.uid())$absl_q$),
    (33, 'public', 'client_error_logs', 'Admins view client error logs', '0008_client_error_log.sql', $absl_q$CREATE POLICY "__absl_check_33"
  ON public.client_error_logs
  FOR SELECT
  TO authenticated
  USING (public.is_admin())$absl_q$),
    (34, 'public', 'client_error_logs', 'Admins acknowledge client error logs', '0008_client_error_log.sql', $absl_q$CREATE POLICY "__absl_check_34"
  ON public.client_error_logs
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin())$absl_q$),
    (35, 'public', 'companies', 'Companies visible to same company and staff', '0024_operator_role_permissions.sql', $absl_q$CREATE POLICY "__absl_check_35"
ON public.companies FOR SELECT
TO authenticated
USING (
  id IN (SELECT company_id FROM public.profiles WHERE profiles.id = auth.uid())
  OR public.current_role() IN ('agent', 'admin', 'technician', 'operator')
)$absl_q$),
    (36, 'public', 'profiles', 'Profiles visible to self and staff', '0024_operator_role_permissions.sql', $absl_q$CREATE POLICY "__absl_check_36"
on public.profiles for select
to authenticated
using (
  id = auth.uid()
  or public.current_role() in ('agent', 'admin', 'operator')
)$absl_q$),
    (37, 'public', 'tickets', 'Staff update tickets', '0024_operator_role_permissions.sql', $absl_q$CREATE POLICY "__absl_check_37"
on public.tickets for update
to authenticated
using (
  assigned_agent_id = auth.uid()
  or assigned_technician_id = auth.uid()
  or public.current_role() in ('agent', 'admin', 'operator')
)
with check (
  assigned_agent_id = auth.uid()
  or assigned_technician_id = auth.uid()
  or public.current_role() in ('agent', 'admin', 'operator')
)$absl_q$),
    (38, 'public', 'callback_requests', 'Staff can view all callback requests', '0024_operator_role_permissions.sql', $absl_q$CREATE POLICY "__absl_check_38"
  ON public.callback_requests
  FOR SELECT
  TO authenticated
  USING (public.current_role() IN ('agent', 'admin', 'operator'))$absl_q$),
    (39, 'public', 'callback_requests', 'Staff can update callback requests', '0024_operator_role_permissions.sql', $absl_q$CREATE POLICY "__absl_check_39"
  ON public.callback_requests
  FOR UPDATE
  TO authenticated
  USING (public.current_role() IN ('agent', 'admin', 'operator'))
  WITH CHECK (public.current_role() IN ('agent', 'admin', 'operator'))$absl_q$),
    (40, 'public', 'admin_alerts', 'Admins can view admin_alerts', '0024_operator_role_permissions.sql', $absl_q$CREATE POLICY "__absl_check_40"
  ON public.admin_alerts
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'operator')
        AND profiles.approval_status = 'approved'
    )
  )$absl_q$),
    (41, 'public', 'admin_alerts', 'Admins can update admin_alerts', '0024_operator_role_permissions.sql', $absl_q$CREATE POLICY "__absl_check_41"
  ON public.admin_alerts
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'operator')
        AND profiles.approval_status = 'approved'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'operator')
        AND profiles.approval_status = 'approved'
    )
  )$absl_q$),
    (42, 'public', 'ticket_attachments', 'Uploader or admin deletes attachment', '0026_allow_deleting_own_service_receipts.sql', $absl_q$CREATE POLICY "__absl_check_42"
ON public.ticket_attachments FOR DELETE
TO authenticated
USING (
  uploaded_by = auth.uid() OR public.is_admin()
)$absl_q$),
    (43, 'storage', 'objects', 'Uploader or admin deletes ticket file', '0026_allow_deleting_own_service_receipts.sql', $absl_q$CREATE POLICY "__absl_check_43"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id IN ('ticket-photos', 'ticket-voice-notes', 'ticket-videos', 'ticket-service-receipts')
  AND (owner = auth.uid() OR public.is_admin())
)$absl_q$);

DROP TABLE IF EXISTS pg_temp.absl_finding;
CREATE TEMP TABLE absl_finding (area text, item text, finding text, source text, optional boolean DEFAULT false);


-- 1. Functions ---------------------------------------------------------
INSERT INTO absl_finding (area, item, finding, source)
SELECT 'function', replace(e.signature, '"', ''),
       CASE
         WHEN p.oid IS NULL THEN 'missing'
         ELSE 'differs from repo: ' || concat_ws(', ',
           CASE WHEN md5(regexp_replace(p.prosrc, '[ \t\n\r\f\v]', '', 'g')) <> e.body_md5 THEN 'body' END,
           CASE WHEN p.prosecdef <> e.secdef THEN 'security definer' END,
           CASE WHEN p.provolatile <> e.volatility THEN 'volatility' END,
           CASE WHEN regexp_replace(coalesce(array_to_string(p.proconfig, ','), ''), '[ ''"]', '', 'g') <> e.config THEN 'search_path' END)
       END,
       e.source
FROM absl_expected_function e
LEFT JOIN pg_proc p ON p.oid = to_regprocedure(e.signature)
WHERE p.oid IS NULL
   OR md5(regexp_replace(p.prosrc, '[ \t\n\r\f\v]', '', 'g')) <> e.body_md5
   OR p.prosecdef <> e.secdef
   OR p.provolatile <> e.volatility
   OR regexp_replace(coalesce(array_to_string(p.proconfig, ','), ''), '[ ''"]', '', 'g') <> e.config;

INSERT INTO absl_finding (area, item, finding, source)
SELECT 'function', p.oid::regprocedure::text, 'left over: not in the migrations (an old version)', ''
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public'
  AND p.prokind = 'f'
  AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid = 'pg_proc'::regclass AND d.objid = p.oid AND d.deptype = 'e')
  AND NOT EXISTS (SELECT 1 FROM absl_expected_function e WHERE to_regprocedure(e.signature) = p.oid);


-- Privileged functions a signed-out visitor can call. Only the helpers
-- that row security evaluates for every visitor should be here, and
-- they are excluded below.
INSERT INTO absl_finding (area, item, finding, source)
SELECT 'function', p.oid::regprocedure::text, 'callable without signing in', ''
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public'
  AND p.prokind = 'f'
  AND p.prosecdef
  AND p.prorettype <> 'trigger'::regtype
  AND has_function_privilege('anon', p.oid, 'EXECUTE')
  AND p.proname NOT IN ('current_role', 'is_staff', 'is_admin', 'can_view_ticket', 'can_access_ticket_file')
  AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid = 'pg_proc'::regclass AND d.objid = p.oid AND d.deptype = 'e');


-- 2. Triggers ----------------------------------------------------------
INSERT INTO absl_finding (area, item, finding, source, optional)
SELECT 'trigger', e.schema_name || '.' || e.table_name || ': ' || e.trigger_name,
       CASE WHEN t.oid IS NULL THEN CASE WHEN e.optional THEN 'not installed (optional - instant emails, see 0020)' ELSE 'missing' END
            ELSE 'calls ' || p.proname || '() instead of ' || e.function_name || '()' END,
       e.source, e.optional AND t.oid IS NULL
FROM absl_expected_trigger e
LEFT JOIN pg_namespace n ON n.nspname = e.schema_name
LEFT JOIN pg_class c ON c.relnamespace = n.oid AND c.relname = e.table_name
LEFT JOIN pg_trigger t ON t.tgrelid = c.oid AND t.tgname = e.trigger_name AND NOT t.tgisinternal
LEFT JOIN pg_proc p ON p.oid = t.tgfoid
WHERE t.oid IS NULL OR p.proname <> e.function_name;

INSERT INTO absl_finding (area, item, finding, source)
SELECT 'trigger', n.nspname || '.' || c.relname || ': ' || t.tgname, 'left over: not in the migrations', ''
FROM pg_trigger t
JOIN pg_class c ON c.oid = t.tgrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public'
  AND NOT t.tgisinternal
  AND NOT EXISTS (SELECT 1 FROM absl_expected_trigger e
                  WHERE e.schema_name = n.nspname AND e.table_name = c.relname AND e.trigger_name = t.tgname);


-- 3. Row security switched on for every app table ----------------------
INSERT INTO absl_finding (area, item, finding, source)
SELECT 'table', 'public.' || c.relname, 'row security is OFF', ''
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p') AND NOT c.relrowsecurity;


-- 4. Policies ----------------------------------------------------------
-- Left over: live rules on the same tables that the migrations don't define.
INSERT INTO absl_finding (area, item, finding, source)
SELECT 'policy', p.schemaname || '.' || p.tablename || ': ' || p.policyname, 'left over: not in the migrations', ''
FROM pg_policies p
WHERE (p.schemaname = 'public' OR (p.schemaname || '.' || p.tablename) IN ('public.companies', 'public.profiles', 'public.tickets', 'public.ticket_comments', 'public.ticket_attachments', 'public.inventory_items', 'public.notifications', 'public.notification_attempts', 'public.callback_requests', 'public.ticket_status_history', 'public.inventory_movements', 'public.audit_logs', 'public.approval_requests', 'storage.objects', 'public.ticket_receipts', 'public.client_error_logs', 'public.admin_alerts'))
  AND NOT EXISTS (SELECT 1 FROM absl_expected_policy e
                  WHERE e.schema_name = p.schemaname AND e.table_name = p.tablename AND e.policy_name = p.policyname);

-- Differs / missing: create each expected rule under a temporary name,
-- compare how Postgres stored it with the live rule, then roll it all back.
DO $absl_check$
DECLARE
  r record;
  v_rows jsonb := '[]'::jsonb;
  v_errors jsonb := '[]'::jsonb;
BEGIN
  BEGIN
    PERFORM set_config('lock_timeout', '5s', true);

    FOR r IN SELECT * FROM absl_expected_policy ORDER BY n LOOP
      BEGIN
        EXECUTE r.check_sql;
      EXCEPTION WHEN OTHERS THEN
        v_errors := v_errors || jsonb_build_object(
          'item', r.schema_name || '.' || r.table_name || ': ' || r.policy_name,
          'finding', 'could not compare: ' || SQLERRM,
          'source', r.source);
      END;
    END LOOP;

    SELECT coalesce(jsonb_agg(jsonb_build_object('item', x.item, 'finding', x.finding, 'source', x.source)), '[]'::jsonb)
    INTO v_rows
    FROM (
      SELECT e.schema_name || '.' || e.table_name || ': ' || e.policy_name AS item,
             e.source,
             CASE WHEN live.policyname IS NULL THEN 'missing'
                  ELSE 'differs from repo: ' || concat_ws(', ',
                    CASE WHEN live.cmd IS DISTINCT FROM chk.cmd THEN 'command' END,
                    CASE WHEN live.roles IS DISTINCT FROM chk.roles THEN 'roles' END,
                    CASE WHEN live.permissive IS DISTINCT FROM chk.permissive THEN 'permissive' END,
                    CASE WHEN live.qual IS DISTINCT FROM chk.qual THEN 'USING' END,
                    CASE WHEN live.with_check IS DISTINCT FROM chk.with_check THEN 'WITH CHECK' END)
             END AS finding
      FROM absl_expected_policy e
      JOIN pg_policies chk
        ON chk.schemaname = e.schema_name AND chk.tablename = e.table_name
       AND chk.policyname = '__absl_check_' || e.n
      LEFT JOIN pg_policies live
        ON live.schemaname = e.schema_name AND live.tablename = e.table_name
       AND live.policyname = e.policy_name
      WHERE live.policyname IS NULL
         OR live.cmd IS DISTINCT FROM chk.cmd
         OR live.roles IS DISTINCT FROM chk.roles
         OR live.permissive IS DISTINCT FROM chk.permissive
         OR live.qual IS DISTINCT FROM chk.qual
         OR live.with_check IS DISTINCT FROM chk.with_check
    ) x;

    RAISE EXCEPTION 'absl_check_rollback';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'absl_check_rollback' THEN
      v_errors := v_errors || jsonb_build_object('item', 'policy comparison', 'finding', 'stopped: ' || SQLERRM, 'source', '');
    END IF;
  END;

  INSERT INTO absl_finding (area, item, finding, source)
  SELECT 'policy', j->>'item', j->>'finding', j->>'source'
  FROM jsonb_array_elements(v_rows || v_errors) AS j;
END
$absl_check$;


-- 5. Result ------------------------------------------------------------
SELECT area, item, finding, source
FROM (
  SELECT 0 AS ord, 'SUMMARY' AS area,
         (SELECT count(*) FROM absl_finding WHERE NOT optional) || ' problem(s)' AS item,
         'checked 32 functions, 43 policies, 18 triggers, row security on every table' AS finding,
         '' AS source
  UNION ALL
  SELECT 1, area, item, finding, source FROM absl_finding
) r
ORDER BY ord, area, item;
